spring.application.name=spring
server.servlet.contextPath=/api/mocks
server.port=8080

#H2 Configuration
spring.datasource.url=jdbc:h2:mem:./mocksH2Db;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user1
spring.datasource.password=user1
spring.sql.init.data-locations=classpath:mocks/pessoa-1_mock.sql
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

#Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
